---
title: Renan Muniz
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Renan Muniz is a software engineer focused on mobile development, author
  of a few open source projects.
baseurl: ''
url: https://renanmuniz.com
twitter_username: renanmunizz
github_username: remunizz
exclude:
- package.json
- node_modules
- gulpfile.js
about:
  description: Software engineer
markdown: kramdown
gems:
- jekyll-sitemap
