---
title: Renan Muniz
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Renan Muniz is a software engineer focused on mobile development, author
  of a few open source projects.
long_description: Software engineer focused on mobile development, with 6 years
  experience, creating systems and mobile apps for companies like Fanta, Ubisoft,
  Light S/A, Ogilvy & Mather, SPTuris and Pearson. Creative environment experience
  and agile methods, currently responsible for the software development of a cool
  startup based in Brazil.    
baseurl: ''
url: https://renanmuniz.com
twitter_username: renanmunizz
github_username: remunizz
exclude:
- package.json
- node_modules
- gulpfile.js
about:
  description: Software engineer
markdown: kramdown
gems:
- jekyll-sitemap
